### ISSUE TITLE
Scaler -> Scalar

### ISSUE THREAD

**Issue by wenkesj** [unixpickle/anyvec#1]
First of all, anyvec makes things ridiculously easier and I'm just now finding a good purpose for the `any` framework. 

Definitely my fault for not reading the documentation thoroughly enough when I was perusing for a method, and in the context of scaling vector magnitude, I think `AddScaler` should be `AddScalar` https://github.com/unixpickle/anyvec/blob/master/vector.go#L60-L61. I don't think this is a breaker, but I was using the `AddScaler` method a lot where I had `AddScalar` spelled out and kept getting issues but for some reason I didn't think to copy&paste or anything. Maybe this is what you meant to do, in that case just ignore this ;)

**Comment by unixpickle** [comment]
Haha, guess this is evidence that I'm an auditory thinker. Technically "scalar" is spelled wrong, just like I'm sure it is in pretty much all numerical code I've ever written. At this point renaming it would probably be more than it's worth, since that would break so many things that depend on anyvec. I'm surprised you don't use anything like auto-complete that could fill in the correct method name.

This reminds me a little of the HTTP "Referer" header--its wrong, but it became right out of necessity.

By the way, it is cases like this that make me long for Go to finally come with a good package manager. If I could bump up the version number for breaking changes, that would be good for things like this.

**Comment by unixpickle** [comment]
**UPDATE:** I decided this is too big a blemish in the codebase to ignore. It doesn't look like there are any other scalar-related breaking changes; AddScaler is the only bad one. As such, I had a script rename AddScaler to AddScalar throughout all of my Github repos.

I recommend that you do a global find-and-replace of "AddScaler" with "AddScalar". This script may help:

```bash
#!/bin/bash

if [ `uname` == 'Darwin' ]; then
    find . -name '*.go' -type f -exec sed -i '' -E 's/AddScaler/AddScalar/g' '{}' \;
else
    find . -name '*.go' -type f -exec sed -i -e 's/AddScaler/AddScalar/g' '{}' \;
fi
```

**Comment by wenkesj** [comment]
@unixpickle swag. Glad you aren't a machine that I create issues with
